services:
  worker:
    build: .
    network_mode: host
    ports:
      - "8501:8501"
    volumes:
      - ~/.streamlit:~/.streamlit
#    environment:
#      FLASK_DEBUG: "true"
#  redis:
#    image: "redis:alpine"
